In [1]:
import numpy as np
import pandas as pd
from copy import deepcopy

In [2]:
link = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
df = pd.read_csv(link)

In [3]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [4]:
df.shape

(9704, 11)

In [5]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

# Q1. Pandas version

In [6]:
#What version of Pandas did you install?
pd.__version__

'2.2.3'

# Q2. Records count

In [7]:
#How many records are in the dataset?
df.shape[0]

9704

# Q3. Fuel types

In [8]:
#How many fuel types are presented in the dataset?
arr = df['fuel_type'].unique()
arr

array(['Gasoline', 'Diesel'], dtype=object)

In [9]:
arr.shape[0]

2

# Q4. Missing values

In [10]:
#How many columns in the dataset have missing values?
s = df.isna().sum(axis=0)
s

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

# Q5. Max fuel efficiency

In [11]:
#What's the maximum fuel efficiency of cars from Asia?
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

# Q6. Median value of horsepower

In [12]:
#Find the median value of the horsepower column in the dataset.
#Next, calculate the most frequent value of the same horsepower column.
#Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
#Now, calculate the median value of horsepower once again.
#Has it changed?
df['horsepower'].median()

149.0

In [13]:
df['horsepower'].value_counts().head()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
Name: count, dtype: int64

In [14]:
df['horsepower'].isna().sum()

708

In [15]:
df1 = df.copy()
df1['horsepower'] = df['horsepower'].fillna(152.0)
df1.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0       152.0     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [16]:
df1['horsepower'].value_counts()

horsepower
152.0    850
145.0    141
151.0    134
141.0    130
148.0    130
        ... 
46.0       1
43.0       1
53.0       1
66.0       1
61.0       1
Name: count, Length: 192, dtype: int64

In [17]:
df1['horsepower'].median()

152.0

# Q7. Sum of weights

In [18]:
#Select all the cars from Asia
#Select only columns vehicle_weight and model_year
#Select the first 7 values
#Get the underlying NumPy array. Let's call it X.
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#Invert XTX.
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#What's the sum of all the elements of the result?
df2 = df[['vehicle_weight', 'model_year', 'origin']]

In [19]:
df2.head()

vehicle_weight  model_year  origin
0     3413.433759        2003  Europe
1     3149.664934        2007     USA
2     3079.038997        2018  Europe
3     2542.392402        2009     USA
4     3460.870990        2009  Europe

In [20]:
df2 = df2[df2['origin'] == 'Asia']

In [21]:
df2.head()

vehicle_weight  model_year origin
8      2714.219310        2016   Asia
12     2783.868974        2010   Asia
14     3582.687368        2007   Asia
20     2231.808142        2011   Asia
21     2659.431451        2016   Asia

In [22]:
df2 = df2.reset_index()

In [23]:
df2.drop('index', axis=1, inplace=True)
df2.drop('origin', axis=1, inplace=True)

In [24]:
X = df2[:7].values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [25]:
X.shape

(7, 2)

In [26]:
XTX = np.dot(X.T,X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [27]:
inv_matrix = np.linalg.inv(XTX)
inv_matrix

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [28]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [29]:
y.shape

(7,)

In [30]:
y.reshape(7,1)

array([[1100],
       [1300],
       [ 800],
       [ 900],
       [1000],
       [1100],
       [1200]])

In [31]:
W = np.dot(np.dot(inv_matrix, X.T), y)
W

array([0.01386421, 0.5049067 ])

In [32]:
W.sum()

0.5187709081074007